name: .NET Core 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v2
    - name: AppSettings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'StoreManager.Api/AppSettings.json'
      env:
        ConnectionStrings.ApplicationConnection: ${{ env.APPLICATIONCONNECTION_DB }}
        ConnectionStrings.IdentityConnection: ${{ env.IDENTITYCONNECTION_DB }}
        MailSettings: ${{ env.MAILSETTINGS }}
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.408
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ./rel/
    - name: Sync Files001
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: putracode.somee.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./rel/
        server-dir: ./www.putracode.somee.com/
        dangerous-clean-slate: true
